spring.application.name=stock

# Configuración del Servidor
# Cambiado a 8081 para que coincida con tu API Gateway
server.port=8085  

# Base de Datos Propia del Microservicio
spring.datasource.url=jdbc:postgresql://localhost:5432/cordillera_db_stock
spring.datasource.username=postgres
spring.datasource.password=12345

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Permite que Hibernate cree las tablas antes de que se ejecute el data.sql
spring.jpa.defer-datasource-initialization=true

# Asegura que el script data.sql se ejecute siempre al iniciar
spring.sql.init.mode=always

